language: node_js
node_js:
  - "8"
  - "9"
  - "10"
addons:
  chrome: stable
sudo: required
cache: yarn
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number"
  - "export PATH="$HOME/.yarn/bin:$PATH""
